# Generated by Django 2.2.4 on 2019-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ailments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, choices=[(1, 'cancer'), (2, 'tb'), (3, 'hayabusa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
                ('air_range', models.IntegerField(null=True)),
                ('ailments', models.ManyToManyField(to='facedetector.Ailments')),
            ],
        ),
    ]
