# Generated by Django 2.2.4 on 2019-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ailments',
            name='disease',
            field=models.CharField(blank=True, choices=[('1', 'cancer'), ('2', 'tb'), ('3', 'hayabusa')], max_length=50),
        ),
    ]
