# Generated by Django 2.2.4 on 2019-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetector', '0002_auto_20190830_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailments',
            name='disease',
            field=models.CharField(blank=True, choices=[('1', 'influenza'), ('2', 'pneumonia'), ('3', 'asthma'), ('4', 'bronchitis'), ('5', 'tb')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
